[package]
name = "gomoku-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gomoku-core = { "path" = "../gomoku-core" }
gomoku-ui = { "path" = "../gomoku-ui" }